src/database/models/contacts.py
import uuid
from pydantic import BaseModel, Field

from src.utils import create_id


class Address(BaseModel):
    """
    Represents an address.

    Attributes:
    - address_id (str): The unique ID of the address.
    - street (str): The street address.
    - city (str): The city.
    - state (str): The state.
    - postal_code (str): The postal code.
    - country (str): The country.
    """

    address_id: str = Field(default_factory=create_id,
                            description="The unique ID of the address.")
    address_line_1: str
    town_city: str
    province: str
    postal_code: str
    country: str


class Contacts(BaseModel):
    contact_id: str = Field(default_factory=create_id)
    cell: str
    tel: str | None
    email: str
    facebook: str | None
    twitter: str | None
    whatsapp: str | None


class PostalAddress(BaseModel):
    postal_id: str = Field(default_factory=create_id)

    address_line_1: str
    town_city: str
    province: str
    postal_code: str
    country: str

src/routes/auth.py
from datetime import timedelta, datetime

from flask import Blueprint, render_template, flash, request, make_response, redirect, Response, \
    url_for
from pydantic import ValidationError

from src.database.models.auth import Auth, RegisterUser
from src.database.models.users import User, CreateUser
from src.logger import init_logger
from src.main import user_controller

auth_route = Blueprint('auth', __name__)
auth_logger = init_logger('auth_logger')
REMEMBER_ME_DELAY = 60 * 60 * 24 * 30


async def create_response(redirect_url, message=None, category=None) -> Response:
    response = make_response(redirect(redirect_url))
    if message and category:
        flash(message=message, category=category)
    return response


@auth_route.get('/login')
async def get_auth():
    context = {}
    return render_template('login.html', **context)


@auth_route.post('/login')
async def do_login():
    try:
        # Phasing out username when login
        auth_user = Auth(**request.form)
    except ValidationError as e:
        auth_logger.error(str(e))
        return await create_response(url_for('auth.get_auth'), 'Login failed. Check your username and password.',
                                     'danger')

    login_user: User | None = await user_controller.login(email=auth_user.email, password=auth_user.password)
    print(f"logged in user: {login_user}")
    if login_user and login_user.email == auth_user.email:
        response = await create_response(url_for('home.get_home'))

        # Setting Loging Cookie
        delay = REMEMBER_ME_DELAY if auth_user.remember == "on" else 30
        expiration = datetime.utcnow() + timedelta(minutes=delay)
        response.set_cookie('auth', value=login_user.uid, expires=expiration, httponly=True)

        if not login_user.account_verified:
            _ = await user_controller.send_verification_email(user=login_user, password=auth_user.password)
            flash(message="A verification email has been sent please verify your email", category="success")
        return response
    else:
        return await create_response(url_for('auth.get_auth'),
                                     'Login failed. please try again', 'danger')


@auth_route.get('/dashboard/logout')
async def do_logout():
    """

    :return:
    """
    # TODO - CHECK IF USER IS ALREADY LOGGED IN
    response = await create_response(url_for('home.get_home'))
    response.delete_cookie('auth')
    flash(message='You have been successfully logged out.', category='danger')
    return response


@auth_route.get('/password-reset')
async def get_password_reset():
    context = {}
    return render_template('password_reset.html', **context)


@auth_route.post('/password-reset')
async def do_password_reset():
    context = {}
    # Check if User Email is available
    # Send Message to User with a link to reset password
    # Flash the message that email was sent with proper details never indicate failure
    flash(message="Message with a link to reset your password has been sent", category='success')
    return render_template('index.html', **context)

@auth_route.get('/register')
async def get_register():
    context = {}
    return render_template('register.html', **context)


@auth_route.post('/register')
async def do_register():
    """
        **do_register**

    :return:
    """
    # TODO - CHECK IF USER IS ALREADY LOGGED IN
    try:
        email = request.form.get('email')
        password = request.form.get('password')
        terms = request.form.get('terms')
        email = email.strip().lower()
        register_user: RegisterUser = RegisterUser(email=email, username=email, password=password, terms=terms)
    except ValidationError as e:
        auth_logger.error(str(e))
        return await create_response(url_for('auth.get_register'), 'Please fill in all the required fields.', 'danger')

    user_exist: User | None = await user_controller.get_by_email(email=register_user.email)
    # user bool test for the conditions necessary to validate the user
    if user_exist:
        flash(message='User Already Exist please login', category='success')
        return await create_response(url_for('auth.get_auth'))
    print(f"Registering user : {register_user}")
    user_data: CreateUser = CreateUser(**register_user.dict(exclude={'terms'}))

    _user_data: User | None = await user_controller.post(user=user_data)
    if _user_data:
        flash(message='Account Successfully created please login', category='success')
        response: Response = await create_response(url_for('auth.get_auth'))
        expiration = datetime.utcnow() + timedelta(minutes=30)
        response.set_cookie('auth', value=user_data.uid, expires=expiration, httponly=True)
        return response

    flash(message='failed to create new user try again later', category='danger')
    return await create_response(url_for('home.get_home'))


@auth_route.get('/dashboard/verify-email')
async def verify_email():
    """
        **verify_email**
        :return:
    """

    token: str = request.args.get('token')
    email: str = request.args.get('email')
    email_verified: bool = await user_controller.verify_email(email=email, token=token)
    if email_verified:
        user: User = await user_controller.get_by_email(email=email)
        user.account_verified = True
        _update_user = await user_controller.put(user=user)
        if _update_user and _update_user.get('account_verified', False):
            flash(message="Account Verified successfully", category="success")
        else:
            flash(message="Your Account could not be verified, please log out", category="danger")
        return redirect(url_for('home.get_home'), code=302)
    flash(message="Unable to verify your email please try again later", category="danger")
    return redirect(url_for('home.get_home'), code=302)

src/routes/cart.py
from flask import Blueprint, render_template, url_for, redirect, flash, request

from src.database.models.contacts import PostalAddress, Address
from src.database.models.orders import Order, OrderItem, OrderStatus
from src.database.models.customers import CustomerDetails
from src.main import customer_controller, product_controller

from src.database.models.products import Product, InventoryEntries, InventoryEntryReasons, Category
from src.authentication import user_details, login_required
from src.database.models.users import User

cart_route = Blueprint('cart', __name__)
from pprint import pprint


@cart_route.get("/shopping-cart")
@user_details
async def get_cart(user: User | None):
    social_url = url_for('cart.get_cart', _external=True)

    # customer_details = await customer_controller.get_customer_details(customer_id=user.customer_id)

    products_list: list[Product] = await product_controller.get_products()
    categories_list: list[Category] = await product_controller.get_categories()

    context = dict(user=user, social_url=social_url, category_list=categories_list, products_list=products_list)
    return render_template('cart/cart.html', **context)


@cart_route.get("/shopping-cart/category/<string:category_name>")
@user_details
async def get_category_products(user: User | None, category_name: str):
    """

    :param user:
    :param category_name:
    :return:
    """
    category_details = await product_controller.get_category_details(category_name=category_name)
    products_list = await product_controller.get_category_products(category_id=category_details.category_id)
    context = dict(user=user, category=category_details, products_list=products_list)
    return render_template('cart/includes/category_products.html', **context)


@cart_route.get("/orders")
@login_required
async def get_orders(user: User | None):
    social_url = url_for('cart.get_orders', _external=True)
    country_list = await customer_controller.get_countries()
    customer_details = await customer_controller.get_customer_details(customer_id=user.customer_id)

    temp_orders: list[Order] = await customer_controller.get_temp_orders(customer_id=user.customer_id)

    context = dict(user=user,
                   country_list=country_list,
                   social_url=social_url,
                   customer=customer_details,
                   current_orders=temp_orders)

    if customer_details and customer_details.postal_id and (customer_details.postal_id == customer_details.delivery_address_id):
        postal_address = await customer_controller.get_postal_address(postal_id=customer_details.postal_id)
        context.update(edit_address=postal_address, postal_address=postal_address, address_type="postal")
        print(f"Postal Address : {postal_address}")
    elif customer_details and customer_details.address_id and (customer_details.address_id == customer_details.delivery_address_id):
        physical_address = await customer_controller.get_address(address_id=customer_details.address_id)
        context.update(edit_address=physical_address, physical_address=physical_address, address_type="physical")
        print(f"Physical Address : {physical_address}")
    else:
        print(f"Why : {customer_details}")
    return render_template('orders/orders.html', **context)


@cart_route.post("/orders/<string:product_id>")
@login_required
async def place_orders(user: User, product_id: str):
    order_quantity = request.form.get('quantity')

    if user.customer_id:
        customer_details: CustomerDetails | None = await customer_controller.get_customer_details(
            customer_id=user.customer_id)
        product_detail: Product | None = await product_controller.get_product(product_id=product_id)

        if customer_details:
            customer_name = f"{customer_details.full_names} {customer_details.surname}"
            email = customer_details.email if customer_details.email else user.email

            temp_order = await customer_controller.get_temp_order(customer_id=user.customer_id)

            if not temp_order:
                temp_order = Order(customer_id=user.customer_id, customer_name=customer_name, email=email,
                                   phone=customer_details.contact_number,
                                   address_id=customer_details.delivery_address_id,
                                   items_ordered=[])

                saved_temp_order = await customer_controller.add_temp_order(order=temp_order)

            order_item = OrderItem(order_id=temp_order.order_id,
                                   product_id=product_id,
                                   product_name=product_detail.name,
                                   price=product_detail.sale_price,
                                   quantity=order_quantity)
            temp_order.items_ordered.append(order_item)
            add_temp_order = await customer_controller.add_temp_order(order=temp_order)
            # add_items_ordered = await customer_controller.add_items_to_temp_order(customer_id=user.customer_id,
            #                                                                       order_id=temp_order.order_id,
            #                                                                       order_item=order_item)
            for order_item in add_temp_order[-1].items_ordered:
                pprint(order_item)
                pprint('-----------------------------------------------------------------------')
            # pprint(f"order: {add_temp_order[-1]}")
        else:

            flash(message="Please Enter Customer Details", category="danger")
            return redirect(url_for('cart.get_orders'))

    flash(message="Order Successfully Captured", category="success")
    return redirect(url_for('cart.get_cart'))


@cart_route.post("/customer/capture")
@login_required
async def capture_customer_details(user: User):
    """

    :param user:
    :return:
    """
    customer_details = CustomerDetails(**request.form, uid=user.uid, customer_id=user.customer_id)
    customer_details_ = await customer_controller.add_customer_details(customer_details=customer_details)
    if customer_details_:
        flash(message="Successfully Captured Customer Details", category="success")
    else:
        flash(message="Unable to save Customer Details", category="danger")
    return redirect(url_for('cart.get_orders'))


@cart_route.post("/customer/capture/delivery_address")
@login_required
async def update_delivery_address(user: User):
    """

    :param user:
    :return:
    """
    address_type = request.form.get("address_type")
    customer_details = await customer_controller.get_customer_details(customer_id=user.customer_id)
    if address_type == "postal":

        postal_address = PostalAddress(**request.form)
        print(f"Setting postal Address: {postal_address}")
        update_postal_address = await customer_controller.add_postal_address(postal_address=postal_address)

        customer_details.postal_id = postal_address.postal_id
        customer_details.delivery_address_id = postal_address.postal_id
    else:
        physical_address = Address(**request.form)
        print(f"Setting physical Address: {physical_address}")
        update_physical_address = await customer_controller.add_update_address(address=physical_address)

        customer_details.address_id = physical_address.address_id
        customer_details.delivery_address_id = physical_address.address_id
    print(f"customer details: {customer_details}")
    customer_details_ = await customer_controller.add_customer_details(customer_details=customer_details)

    flash(message="Successfully Updated Delivery Address Details", category="success")
    return redirect(url_for('cart.get_orders'))


@cart_route.get("/customer/order/edit/<string:order_id>")
@login_required
async def edit_order(user: User, order_id: str):
    """

    :param user:
    :param order_id:
    :return:
    """

    order: Order = await customer_controller.get_temp_order(customer_id=user.customer_id)
    context = dict(user=user, order=order)
    return render_template('orders/modals/edit.html', **context)


@cart_route.post("/customer/order/edit/<string:order_id>")
@login_required
async def update_order(user: User, order_id: str):
    """

    :param user:
    :param order_id:
    :return:
    """
    print(request.form)
    updated_quantities = {}
    for key, value in request.form.items():
        if key.startswith('quantity_'):
            item_id = key.replace('quantity_', '')
            updated_quantities[item_id] = int(value)

    order: Order = await customer_controller.get_temp_order(customer_id=user.customer_id)

    # Update quantities in the order
    for item in order.items_ordered:
        if item.item_id in updated_quantities:
            item.quantity = updated_quantities[item.item_id]
    updated_order = await customer_controller.add_temp_order(order=order)
    if updated_order:
        order = updated_order[-1]
    flash(message="Order Updated", category="success")
    context = dict(user=user, order=order)

    return render_template('orders/modals/edit.html', **context)


@cart_route.get("/customer/order/view/<string:order_id>")
@login_required
async def get_order(user: User, order_id: str):
    """

    :param user:
    :param order_id:
    :return:
    """
    pass


@cart_route.get("/customer/order/finalize/<string:order_id>")
@login_required
async def finalize_order(user: User, order_id: str):
    """
    """
    customer = await customer_controller.get_customer_details(customer_id=user.customer_id)
    order = await customer_controller.get_order_by_order_id(customer_id=user.customer_id, order_id=order_id)

    order = Order(**order.dict())
    order.status = OrderStatus.PENDING.value
    # _stored_order = await customer_controller.store_order_to_database(order=order)
    context = dict(user=user, order=order, customer=customer)

templates/about.html
{% extends "layouts/page.html" %}

{% block content %}
{% include "layouts/social.html" %}
<section id="main-content">
    <div class="card">
        <div class="card-header">
            <h3 class="card-title">About Zwavhudivhudi Electrical &amp; Projects</h3>
        </div>

    </div>

</section>

{% endblock %}

templates/contact.html
{% extends "layouts/page.html" %}

{% block content %}
{% include "layouts/social.html" %}
<section id="main-content">
    <div class="card">
        <div class="card-body">
            <div class="card-header">
                <h2 class="card-title font-weight-bold text-info">
                    <i class="fa fa-envelope-square"> </i>
                    Contact Us
                </h2>
                <p class="font-weight-bold">Feel free to contact us for any inquiries or feedback.</p>
            </div>
            <div class="row">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">Zwavhudivhudi Electrical &amp; Projects <small class="text-info"></small></h3>
                    </div>

                    <div class="card-header">
                        <h3 class="card-title font-weight-bold text-info">
                            <i class="fa fa-inbox"> </i>
                            Contact Form
                        </h3>
                    </div>
                    <form action="{{ url_for('home.send_contact') }}" method="post">
                        <div class="form-group">
                            <label for="name" class="lsbel text-info font-weight-bold">Name:</label>
                            <input type="text" class="form-control" id="name" name="name" required>
                        </div>
                        <div class="form-group">
                            <label for="email" class="lsbel text-info font-weight-bold">Email:</label>
                            <input type="email" class="form-control" id="email" name="email" required>
                        </div>
                        <div class="form-group">
                            <label for="message" class="lsbel text-info font-weight-bold">Message:</label>
                            <textarea class="col-12" id="message" name="message" rows="4" required></textarea>
                        </div>
                        <button type="submit" class="btn btn-primary font-weight-bold">
                            <i class="fa fa-send-o"> </i>
                            Send Message
                        </button>
                    </form>
                </div>

            </div>
            <hr/>

        </div>
    </div>
</section>

{% endblock %}

templates/faq.html
{% extends "layouts/page.html" %}

{% block content %}

<section id="main-content">
    <div class="card">
        <div class="card-header">
            <h2 class=""> FAQ</h2>
        </div>
        <div class="card-body">
        </div>


    </div>

</section>

{% endblock %}

templates/how.html
{% extends "layouts/page.html" %}
{% block custom_css %}
<style>
    .faq-item {
        margin-bottom: 20px;
    }

    .faq-item h3 {
        cursor: pointer;
    }

    .answer {
        display: none;
    }
</style>
{% endblock %}
{% block content %}
<section id="main-content">

</section>




{% endblock %}

{% block scripts %}
<script>
    function toggleAnswer(id) {
        var answer = document.getElementById(id);
        if (answer.style.display === "block") {
            answer.style.display = "none";
        } else {
            answer.style.display = "block";
        }
    }
</script>
{% endblock %}

templates/index.html
{% extends "layouts/page.html" %}
{% block custom_css %}
<link href="{{ url_for('static', filename='css/custom.css') }}" rel="stylesheet">
{% endblock %}
{% block content %}
<section id="main-content">
    <div class="card">
        <div class="card-header">
            <h1 class="card-title font-weight-bold ">
                Zwavhudivhudi Electrical &amp; Projects
            </h1>
        </div>
        <div class="scrollable-row">
            {% for category in category_list %}
                <div class="row fluid">
                    <!-- Image Column -->
                    <div class="card-body">
                        <img alt="{{ category.name }}" src="{{ url_for('static', filename=category.img_link|safe) }}" class="img-fluid" />
                        <h2 class="card-title font-weight-bold text-info">{{ category.name|title }}</h2>
                        <p class="font-weight-bold text-info fluid" style="max-width: 200px;">{{ category.description[:35] }}{% if category.description|length > 35 %}...{% endif %}</p>
                        <div class="card-footer">
                            <a href="{{ url_for('cart.get_category_products', category_name=category.name) }}"
                               class="btn btn-sm btn-rounded btn-primary align-content-center w-100"
                            >
                            <i class="fa fa-folder-open"> </i>
                                Open
                            </a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>

    </div>
</section>

{% endblock %}

templates/login.html
{% extends "layouts/auth.html" %}

{% block content %}
<!--suppress ALL -->
<div class="login-content">
    <div class="login-logo">
        <a href="{{ url_for('home.get_home' )}}"><span>Zwavhudivhudi Electrical &amp; Projects</span></a>
    </div>
    {% include "layouts/flash.html" %}
    <div class="login-form">
        <h4 class="font-weight-bold text-info">Login</h4>
        <label class="font-weight-bold text-info">Login to start using funeral admin</label>

        <form action="{{ url_for('auth.do_login')}}" method="POST"  enctype="multipart/form-data">
            <div class="form-group">
                <label for="username">Email address</label>
                <input type="email" class="form-control" id="email" name="email" placeholder="Email">
            </div>

            <div class="form-group">
                <label for="password">Password</label>
                <input type="password" class="form-control" id="password" name="password" placeholder="Password">
            </div>
            <div class="checkbox">
                <label>
                    <input type="checkbox" name="remember"> Remember Me
                </label>
                <label class="pull-right">
                    <a href="{{ url_for('auth.get_password_reset') }}">Forgotten Password?</a>
                </label>
            </div>
            <button type="submit" class="btn btn-primary btn-flat m-b-30 m-t-30">Sign in</button>
            <div class="register-link m-t-15 text-center font-weight-bold">
                <p>Don't have an account? <a href="{{ url_for('auth.get_register')}}">Sign Up Here</a></p>
            </div>
        </form>

    </div>
</div>
{% endblock %}

templates/market_listing.html
{% extends "layouts/page.html" %}

{% block content %}

<section id="main-content">
    <div class="card">
        <div class="card-header">
            <h2 class=""> Market Listing</h2>
        </div>
        <div class="card-body">
        </div>


    </div>

</section>

{% endblock %}

templates/password_reset.html
{% extends "layouts/auth.html" %}

{% block content %}
<div class="login-content">

    <div class="login-logo">
        <a href="{{ url_for('home.get_home') }}"><span>Zwavhudivhudi Electrical &amp; Projects</span></a>
    </div>
    {% include "layouts/flash.html" %}
    <div class="login-form">
        <h4>Reset Password</h4>
        <form action="{{ url_for('auth.do_password_reset') }}" method="POST"  enctype="multipart/form-data">
            <div class="form-group">
                <label>Email address</label>
                <input type="email" class="form-control" name="email" placeholder="Email">
            </div>
            <button type="submit" class="btn btn-primary btn-flat m-b-15">Submit</button>
            <div class="register-link text-center">
                <p>Back to <a href="{{ url_for('home.get_home') }}"> Home</a></p>
            </div>
        </form>
    </div>
</div>
{% endblock %}

templates/register.html
{% extends "layouts/auth.html" %}

{% block content %}
<div class="login-content">

    <div class="login-logo">
       <a href="{{ url_for('home.get_home') }}"><span>Zwavhudivhudi Electrical &amp; Projects</span></a>
    </div>


    {% include "layouts/flash.html" %}
    <div class="login-form">
        <h4 class="font-weight-bold text-info">Create New Login Account</h4>
        <label class="font-weight-bold text-danger">create an account to use this service - ensure your password is unique</label>
        <form action="{{ url_for('auth.do_register') }}" method="POST"  enctype="multipart/form-data">
{#            <div class="form-group">#}
{#                <label for="username">User Name</label>#}
{#                <input type="text" class="form-control" id="username" name="username" placeholder="User Name">#}
{#            </div>#}
{##}
            <div class="form-group">
                <label for="email">Email address</label>
                <input type="email" class="form-control" id="email" name="email" placeholder="Email">
            </div>
            <div class="form-group">
                <label for="password">Password</label>
                <input type="password" class="form-control" id="password" name="password" placeholder="Password">
            </div>
            <div class="checkbox">
                <label class="font-weight-bold">
                    <input type="checkbox" name="terms"> Agree the terms and policy
                </label>
            </div>
            <button type="submit" class="btn btn-primary btn-flat m-b-30 m-t-30">Register</button>
            <div class="register-link m-t-15 text-center font-weight-bold">
                <p>Already have account ? <a href="{{ url_for('auth.get_auth') }}"> Sign in</a></p>
            </div>
        </form>
    </div>
</div>
{% endblock %}

templates/verification.html
{% extends "layouts/page.html" %}

{% block content %}

<section id="main-content">
    <div class="card">
        <div class="card-header">
            <h2>Account Verification</h2>
            <label class="font-weight-bold text-danger">
                ONLY VERIFY GAME ACCOUNTS YOU INTEND TO SELL
            </label>
        </div>
        <div class="card-footer">
            <blockquote class="font-weight-bold text-warning">
                Note that your game Email should not necessarily be the same email address you used for creating this account and vice versa
            </blockquote>
        </div>
        <div class="card-body">
        <form class="form-horizontal" action="{{ url_for('profile.do_verification')}}" method="POST">
            <input type="hidden"  name="game_id" value="{{ user.game_id }}">
            <div class="form-group">
                <label class="label font-weight-bold"> Game Email </label>
                <input name="game_email" type="text" class="form-control">
            </div>
            <div class="form-group">
                <label class="label font-weight-bold"> Game Password </label>
                <input name="game_password" type="text" class="form-control">
            </div>
            <div class="form-group">
                <label class="label font-weight-bold"> Game Pin </label>
                <input name="game_pin" type="text" class="form-control">
            </div>
            <div class="form-group">
                <button type="submit" class="btn btn-primary btn-sm">
                    <i class="ti-location-pin"> </i>
                    Verify</button>
            </div>
            <div class="form-group">
                <label class="font-weight-bold text-info">Verification usually takes 1 to 3 hours upon which your Game Account will be marked as verified</label>
            </div>
        </form>
        </div>
    </div>
</section>

{% endblock %}