src/database/models/orders.py
from pydantic import BaseModel, Field
from enum import Enum
from datetime import datetime
from src.utils import create_order_number


def create_date() -> str:
    return datetime.now().strftime("%Y-%m-%d %H:%M:%S")


class OrderStatus(Enum):
    INCOMPLETE = "Incomplete"
    PENDING = 'Pending'
    PROCESSING = 'Processing'
    SHIPPED = 'Shipped'
    DELIVERED = 'Delivered'
    CANCELLED = 'Cancelled'


class OrderItem(BaseModel):

    item_id: str = Field(default_factory=create_order_number)
    order_id: str
    product_id: str
    product_name: str
    price: int
    quantity: int
    discount_percent: int = Field(default=0)

    def __eq__(self, other):
        return (self.item_id == other.item_id) and (self.order_id == other.order_id)

    @property
    def total_price(self) -> int:
        """Calculate total price of the ordered products"""

        return int(self.price * self.quantity)

    @property
    def total_discount(self) -> int:
        return int(self.price * self.discount_percent / 100)


class Order(BaseModel):

    order_id: str = Field(default_factory=create_order_number)
    customer_id: str
    customer_name: str
    email: str
    phone: str
    address_id: str | None
    order_datetime: str = Field(default_factory=create_date)
    status: str = Field(default=OrderStatus.INCOMPLETE.value)

    items_ordered: list[OrderItem]

    def __eq__(self, other):
        return (self.order_id == other.order_id) and (self.customer_id == other.customer_id)

    @property
    def total_price(self) -> int:
        """Calculate total price of the order"""
        return sum(item.total_price for item in self.items_ordered)

    @property
    def total_discount(self) -> int:
        return sum(item.total_discount for item in self.items_ordered)

    @property
    def quantity(self) -> int:
        """calculates total items on order"""
        return len(self.items_ordered)

    @property
    def time_since_ordered(self) -> int:
        """
            Calculates the time since order was placed in minutes
        """
        order_date = datetime.fromisoformat(self.order_datetime)
        time_difference = datetime.now() - order_date
        return int(time_difference.total_seconds() // 60)  # Convert to minutes

src/routes/cart.py
from flask import Blueprint, render_template, url_for, redirect, flash, request

from src.database.models.contacts import PostalAddress, Address
from src.database.models.orders import Order, OrderItem, OrderStatus
from src.database.models.customers import CustomerDetails
from src.main import customer_controller, product_controller

from src.database.models.products import Product, InventoryEntries, InventoryEntryReasons, Category
from src.authentication import user_details, login_required
from src.database.models.users import User

cart_route = Blueprint('cart', __name__)
from pprint import pprint


@cart_route.get("/shopping-cart")
@user_details
async def get_cart(user: User | None):
    social_url = url_for('cart.get_cart', _external=True)

    # customer_details = await customer_controller.get_customer_details(customer_id=user.customer_id)

    products_list: list[Product] = await product_controller.get_products()
    categories_list: list[Category] = await product_controller.get_categories()

    context = dict(user=user, social_url=social_url, category_list=categories_list, products_list=products_list)
    return render_template('cart/cart.html', **context)


@cart_route.get("/shopping-cart/category/<string:category_name>")
@user_details
async def get_category_products(user: User | None, category_name: str):
    """

    :param user:
    :param category_name:
    :return:
    """
    category_details = await product_controller.get_category_details(category_name=category_name)
    products_list = await product_controller.get_category_products(category_id=category_details.category_id)
    context = dict(user=user, category=category_details, products_list=products_list)
    return render_template('cart/includes/category_products.html', **context)


@cart_route.get("/orders")
@login_required
async def get_orders(user: User | None):
    social_url = url_for('cart.get_orders', _external=True)
    country_list = await customer_controller.get_countries()
    customer_details = await customer_controller.get_customer_details(customer_id=user.customer_id)

    temp_orders: list[Order] = await customer_controller.get_temp_orders(customer_id=user.customer_id)

    context = dict(user=user,
                   country_list=country_list,
                   social_url=social_url,
                   customer=customer_details,
                   current_orders=temp_orders)

    if customer_details and customer_details.postal_id and (customer_details.postal_id == customer_details.delivery_address_id):
        postal_address = await customer_controller.get_postal_address(postal_id=customer_details.postal_id)
        context.update(edit_address=postal_address, postal_address=postal_address, address_type="postal")
        print(f"Postal Address : {postal_address}")
    elif customer_details and customer_details.address_id and (customer_details.address_id == customer_details.delivery_address_id):
        physical_address = await customer_controller.get_address(address_id=customer_details.address_id)
        context.update(edit_address=physical_address, physical_address=physical_address, address_type="physical")
        print(f"Physical Address : {physical_address}")
    else:
        print(f"Why : {customer_details}")
    return render_template('orders/orders.html', **context)


@cart_route.post("/orders/<string:product_id>")
@login_required
async def place_orders(user: User, product_id: str):
    order_quantity = request.form.get('quantity')

    if user.customer_id:
        customer_details: CustomerDetails | None = await customer_controller.get_customer_details(
            customer_id=user.customer_id)
        product_detail: Product | None = await product_controller.get_product(product_id=product_id)

        if customer_details:
            customer_name = f"{customer_details.full_names} {customer_details.surname}"
            email = customer_details.email if customer_details.email else user.email

            temp_order = await customer_controller.get_temp_order(customer_id=user.customer_id)

            if not temp_order:
                temp_order = Order(customer_id=user.customer_id, customer_name=customer_name, email=email,
                                   phone=customer_details.contact_number,
                                   address_id=customer_details.delivery_address_id,
                                   items_ordered=[])

                saved_temp_order = await customer_controller.add_temp_order(order=temp_order)

            order_item = OrderItem(order_id=temp_order.order_id,
                                   product_id=product_id,
                                   product_name=product_detail.name,
                                   price=product_detail.sale_price,
                                   quantity=order_quantity)
            temp_order.items_ordered.append(order_item)
            add_temp_order = await customer_controller.add_temp_order(order=temp_order)
            # add_items_ordered = await customer_controller.add_items_to_temp_order(customer_id=user.customer_id,
            #                                                                       order_id=temp_order.order_id,
            #                                                                       order_item=order_item)
            for order_item in add_temp_order[-1].items_ordered:
                pprint(order_item)
                pprint('-----------------------------------------------------------------------')
            # pprint(f"order: {add_temp_order[-1]}")
        else:

            flash(message="Please Enter Customer Details", category="danger")
            return redirect(url_for('cart.get_orders'))

    flash(message="Order Successfully Captured", category="success")
    return redirect(url_for('cart.get_cart'))


@cart_route.post("/customer/capture")
@login_required
async def capture_customer_details(user: User):
    """

    :param user:
    :return:
    """
    customer_details = CustomerDetails(**request.form, uid=user.uid, customer_id=user.customer_id)
    customer_details_ = await customer_controller.add_customer_details(customer_details=customer_details)
    if customer_details_:
        flash(message="Successfully Captured Customer Details", category="success")
    else:
        flash(message="Unable to save Customer Details", category="danger")
    return redirect(url_for('cart.get_orders'))


@cart_route.post("/customer/capture/delivery_address")
@login_required
async def update_delivery_address(user: User):
    """

    :param user:
    :return:
    """
    address_type = request.form.get("address_type")
    customer_details = await customer_controller.get_customer_details(customer_id=user.customer_id)
    if address_type == "postal":

        postal_address = PostalAddress(**request.form)
        print(f"Setting postal Address: {postal_address}")
        update_postal_address = await customer_controller.add_postal_address(postal_address=postal_address)

        customer_details.postal_id = postal_address.postal_id
        customer_details.delivery_address_id = postal_address.postal_id
    else:
        physical_address = Address(**request.form)
        print(f"Setting physical Address: {physical_address}")
        update_physical_address = await customer_controller.add_update_address(address=physical_address)

        customer_details.address_id = physical_address.address_id
        customer_details.delivery_address_id = physical_address.address_id
    print(f"customer details: {customer_details}")
    customer_details_ = await customer_controller.add_customer_details(customer_details=customer_details)

    flash(message="Successfully Updated Delivery Address Details", category="success")
    return redirect(url_for('cart.get_orders'))


@cart_route.get("/customer/order/edit/<string:order_id>")
@login_required
async def edit_order(user: User, order_id: str):
    """

    :param user:
    :param order_id:
    :return:
    """

    order: Order = await customer_controller.get_temp_order(customer_id=user.customer_id)
    context = dict(user=user, order=order)
    return render_template('orders/modals/edit.html', **context)


@cart_route.post("/customer/order/edit/<string:order_id>")
@login_required
async def update_order(user: User, order_id: str):
    """

    :param user:
    :param order_id:
    :return:
    """
    print(request.form)
    updated_quantities = {}
    for key, value in request.form.items():
        if key.startswith('quantity_'):
            item_id = key.replace('quantity_', '')
            updated_quantities[item_id] = int(value)

    order: Order = await customer_controller.get_temp_order(customer_id=user.customer_id)

    # Update quantities in the order
    for item in order.items_ordered:
        if item.item_id in updated_quantities:
            item.quantity = updated_quantities[item.item_id]
    updated_order = await customer_controller.add_temp_order(order=order)
    if updated_order:
        order = updated_order[-1]
    flash(message="Order Updated", category="success")
    context = dict(user=user, order=order)

    return render_template('orders/modals/edit.html', **context)


@cart_route.get("/customer/order/view/<string:order_id>")
@login_required
async def get_order(user: User, order_id: str):
    """

    :param user:
    :param order_id:
    :return:
    """
    pass


@cart_route.get("/customer/order/finalize/<string:order_id>")
@login_required
async def finalize_order(user: User, order_id: str):
    """
    """
    customer = await customer_controller.get_customer_details(customer_id=user.customer_id)
    order = await customer_controller.get_order_by_order_id(customer_id=user.customer_id, order_id=order_id)

    order = Order(**order.dict())
    order.status = OrderStatus.PENDING.value
    # _stored_order = await customer_controller.store_order_to_database(order=order)
    context = dict(user=user, order=order, customer=customer)

templates/orders/orders.html
{% extends "layouts/page.html" %}

{% block content %}
{% include "layouts/social.html" %}
<section id="main-content">
    <div class="card">
        <div class="card-header">
            <h3 class="card-title font-weight-bold text-info">
                <i class="fa fa-shopping-cart"></i>
                Place Your Order
            </h3>
        </div>
        <div class="card-body">
            {% if customer %}
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">Customer Details</h3>
                    </div>
                    <div class="card-body">
                        <ul>
                            <li class="font-weight-bold text-info m-t-8">First Names : {{ customer.full_names }}</li>
                            <li class="font-weight-bold text-info m-t-8">Surname: {{ customer.surname }}</li>
                            <li class="font-weight-bold text-info m-t-8">Cell: {{ customer.contact_number }}</li>
                            {% if customer.delivery_address_id %}
                                <li class="font-weight-bold text-info m-t-8">Delivery To:
                                    {% if postal_address %}
                                    <ol>
                                        <li class="font-weight-bold text-info m-b-8">Postal Address </li>
                                        <li class="font-weight-bold text-info m-t-4">Box / Private Bag: {{ postal_address.address_line_1 }}</li>
                                        <li class="font-weight-bold text-info m-t-4">Town / City: {{ postal_address.town_city }}</li>
                                        <li class="font-weight-bold text-info m-t-4">Province: {{ postal_address.province }}</li>
                                        <li class="font-weight-bold text-info m-t-4">Postal Code: {{ postal_address.postal_code }}</li>
                                        <li class="font-weight-bold text-info m-t-4">
                                            <a href="#" class="btn btn-sm btn-primary" data-toggle="modal" data-target="#addDeliveryAddress">
                                                <i class="fa fa-car"> </i>
                                                Edit Address
                                            </a>
                                        </li>
                                    </ol>
                                    {% endif %}
                                    {% if physical_address %}
                                    <ol>
                                        <li class="font-weight-bold text-info m-b-8">Physical Address</li>
                                        <li class="font-weight-bold text-info m-t-4">Street: {{ physical_address.street }}</li>
                                        <li class="font-weight-bold text-info m-t-4">Town / City: {{ physical_address.city }}</li>
                                        <li class="font-weight-bold text-info m-t-4">Province: {{ physical_address.state_province }}</li>
                                        <li class="font-weight-bold text-info m-t-4">Postal Code: {{ physical_address.postal_code }}</li>
                                        <li class="font-weight-bold text-info m-t-4">Country: {{ physical_address.country }}</li>
                                        <li class="font-weight-bold text-info m-t-4">
                                            <a href="#" class="btn btn-sm btn-primary" data-toggle="modal" data-target="#addDeliveryAddress">
                                                <i class="fa fa-car"> </i>
                                                Edit Address
                                            </a>
                                        </li>

                                    </ol>
                                    {% endif %}
                                </li>
                            {% else %}
                                 <li class="m-t-12">
                                    <a href="#" class="btn btn-sm btn-primary" data-toggle="modal" data-target="#addDeliveryAddress">
                                        <i class="fa fa-car"> </i>
                                        Add Delivery Address
                                    </a>
                                 </li>
                            {% endif %}
                        </ul>
                    </div>
                </div>
            {% else %}
                <div class="card">
                <div class="card-header">
                    <h3 class="card-title font-weight-bold text-info">
                        <i class="fa fa-user"></i>
                        Customer Details
                    </h3>
                </div>
                    <form id="customer_details" method="POST" action="{{ url_for('cart.capture_customer_details') }}">
                        <div class="form-group">
                            <label for="customerName" class="font-weight-bold">Your Name:</label>
                            <input type="text" class="form-control" id="full_names" name="full_names" required>
                        </div>
                        <div class="form-group">
                            <label for="surname" class="font-weight-bold">Surname:</label>
                            <input type="text" class="form-control" id="surname" name="surname" required>
                        </div>

                        <div class="form-group">
                            <label for="email" class="font-weight-bold">Email:</label>
                            <input type="email" class="form-control" id="email" name="email" required>
                        </div>

                        <div class="form-group">
                            <label for="contact_number" class="font-weight-bold">Phone Number:</label>
                            <input type="tel" class="form-control" id="contact_number" name="contact_number" required>
                        </div>
                        <button type="submit" class="btn btn-success mt-3">
                            <i class="fa fa-user-circle"> </i>
                            Customer Details
                        </button>
                    </form>
                </div>

            {% endif %}

        </div>
    </div>

    <!-- View Current Orders Section -->
<!-- View Current Orders Section -->
<div class="card mt-4">
    <div class="card-header">
        <h3 class="card-title font-weight-bold text-info">
            <i class="fa fa-list-alt"></i>
            Current Orders
        </h3>
    </div>
    <div class="card-body">
        {% if current_orders %}
        <div class="table-responsive">
            <table class="table table-bordered table-striped">
                <thead>
                    <tr>
                        <th>Order Number</th>
                        <th>Order Date</th>
                        <th>Status</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    {% for order in current_orders %}
                    <tr>
                        <td><a href="{{ url_for('cart.get_order', order_id=order.order_id) }}" class="btn btn-primary btn-sm">
                            <i class="fa fa-search-plus"> </i>
                            {{ order.order_id }}
                        </a></td>
                        <td>{{ order.order_datetime }}</td>
                        <td>{{ order.status }}</td>
                        <td>
                            <a href="{{ url_for('cart.edit_order', order_id=order.order_id) }}" class="btn btn-primary btn-sm">
                                <i class="fa fa-edit"> </i>
                                Edit
                            </a>
                            <a href="{{ url_for('cart.finalize_order', order_id=order.order_id) }}" class="btn btn-primary btn-sm">
                                <i class="fa fa-shopping-basket"> </i>
                                Checkout
                            </a>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        {% else %}
        <p>No current orders found.</p>
        {% endif %}
    </div>
</div>

    <!-- View Previous Orders Section -->
    <div class="card mt-4">
        <div class="card-header">
            <h3 class="card-title font-weight-bold text-info">
                <i class="fa fa-history"></i>
                Previous Orders
            </h3>
        </div>
        <div class="card-body">
            <!-- Display previous orders here -->
            <p>No previous orders found.</p>
        </div>
    </div>


</section>

{% endblock %}


{% include "orders/modals/delivery_address.html" %}